#define DEBUG_SPRITETEXTURE_LOADED 1 // DISPLAY MESSAGES WHEN TEXTURE LOADING SUCCEEDS
#define DEBUG_MOBTRANSIT_RAYCAST 1 // RAYCAST - ENTITY TARGET LOCATION
#define DEBUG_MOBTRANSIT_ROAMREACHED // ROAM TARGET LOCATION REACHED
#define DEBUG_MOBTRANSIT_ROAMNOTREACHED // ROAM TARGET LOCATION : IN TRANSIT
#define DEBUG_DENIED_PLAYERACTION 1 //DENIED PLAYER ACTIONS